apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: githubaction-new
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "githubaction-new-cloud-platform-reference-app-github-action-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts:
    - cp-reference-github-actions-new.apps.live.cloud-platform.service.justice.gov.uk
    secretName: {{ .secretName }}
  rules:
    - host: cp-reference-github-actions-new.apps.live.cloud-platform.service.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  name: http
